export const GridData = [
  {
    id: 1,
    nameLang: {
      "en-US": "Raja Kumar",
      "kn-IN": "ರಾಜ ಕುಮಾರ್",
      "ta-IN": "ராஜா குமார்",
      "hi-IN": "राजा कुमार",
      "te-IN": "రాజా కుమార్",
      "ar-SA": "راجا كومار",
      "ml-IN": "രാജ കുമാർ",
    },
    active: true,
    updatedAt: "2024-11-15T10:30:45Z",
  },
  {
    id: 2,
    nameLang: {
      "en-US": "Priya Sharma",
      "kn-IN": "ಪ್ರಿಯಾ ಶರ್ಮಾ",
      "ta-IN": "ப்ரியா சர்மா",
      "hi-IN": "प्रिया शर्मा",
      "te-IN": "ప్రియ శర్మ",
      "ar-SA": "بريا شارما",
      "ml-IN": "പ്രിയ ശർമ",
    },
    active: true,
    updatedAt: "2024-12-01T14:22:17Z",
  },
  {
    id: 3,
    nameLang: {
      "en-US": "Arun Patel",
      "kn-IN": "ಅರುಣ್ ಪಟೇಲ್",
      "ta-IN": "அருண் படேல்",
      "hi-IN": "अरुण पटेल",
      "te-IN": "అరుణ్ పటేల్",
      "ar-SA": "أرون باتيل",
      "ml-IN": "അരുൺ പട്ടേൽ",
    },
    active: true,
    updatedAt: "2025-01-10T09:15:23Z",
  },
  {
    id: 4,
    nameLang: {
      "en-US": "Lakshmi Nair",
      "kn-IN": "ಲಕ್ಷ್ಮಿ ನಾಯರ್",
      "ta-IN": "லட்சுமி நாயர்",
      "hi-IN": "लक्ष्मी नायर",
      "te-IN": "లక్ష్మి నాయర్",
      "ar-SA": "لاكشمي ناير",
      "ml-IN": "ലക്ഷ്മി നായർ",
    },
    active: true,
    updatedAt: "2024-10-20T16:40:12Z",
  },
  {
    id: 5,
    nameLang: {
      "en-US": "Vikram Singh",
      "kn-IN": "ವಿಕ್ರಮ್ ಸಿಂಗ್",
      "ta-IN": "விக்ரம் சிங்",
      "hi-IN": "विक्रम सिंह",
      "te-IN": "విక్రమ్ సింగ్",
      "ar-SA": "فيكرام سينغ",
      "ml-IN": "വിക്രം സിംഗ്",
    },
    active: false,
    updatedAt: "2025-03-05T11:55:30Z",
  },
  {
    id: 6,
    nameLang: {
      "en-US": "Anjali Menon",
      "kn-IN": "ಅಂಜಲಿ ಮೆನನ್",
      "ta-IN": "அஞ்சலி மேனன்",
      "hi-IN": "अंजलि मेनन",
      "te-IN": "అంజలి మేనన్",
      "ar-SA": "أنجالي مينون",
      "ml-IN": "അഞ്ജലി മേനോൻ",
    },
    active: false,
    updatedAt: "2024-09-12T08:25:19Z",
  },
  {
    id: 7,
    nameLang: {
      "en-US": "Suresh Reddy",
      "kn-IN": "ಸುರೇಶ್ ರೆಡ್ಡಿ",
      "ta-IN": "சுரேஷ் ரெட்டி",
      "hi-IN": "सुरेश रेड्डी",
      "te-IN": "సురేష్ రెడ్డి",
      "ar-SA": "سوريش ريدي",
      "ml-IN": "സുരേഷ് റെഡ്ഡി",
    },
    active: true,
    updatedAt: "2025-02-28T13:10:07Z",
  },
  {
    id: 8,
    nameLang: {
      "en-US": "Meena Iyer",
      "kn-IN": "ಮೀನಾ ಐಯರ್",
      "ta-IN": "மீனா ஐயர்",
      "hi-IN": "मीना अय्यर",
      "te-IN": "మీనా అయ్యర్",
      "ar-SA": "مينا آيير",
      "ml-IN": "മീന ഐയർ",
    },
    active: true,
    updatedAt: "2024-08-30T17:35:41Z",
  },
  {
    id: 9,
    nameLang: {
      "en-US": "Kiran Desai",
      "kn-IN": "ಕಿರಣ್ ದೇಸಾಯಿ",
      "ta-IN": "கிரண் தேசாய்",
      "hi-IN": "किरण देसाई",
      "te-IN": "కిరణ్ దేశాయి",
      "ar-SA": "كيران ديساي",
      "ml-IN": "കിരൺ ദേശായി",
    },
    active: true,
    updatedAt: "2025-04-01T12:20:55Z",
  },
  {
    id: 10,
    nameLang: {
      "en-US": "Ahmed Khan",
      "kn-IN": "ಅಹ್ಮದ್ ಖಾನ್",
      "ta-IN": "அகமது கான்",
      "hi-IN": "अहमद खान",
      "te-IN": "అహ్మద్ ఖాన్",
      "ar-SA": "أحمد خان",
      "ml-IN": "അഹമ്മദ് ഖാൻ",
    },
    active: true,
    updatedAt: "2024-07-22T09:45:33Z",
  },
  {
    id: 11,
    nameLang: {
      "en-US": "Deepa Rao",
      "kn-IN": "ದೀಪಾ ರಾವ್",
      "ta-IN": "தீபா ராவ்",
      "hi-IN": "दीपा राव",
      "te-IN": "దీపా రావు",
      "ar-SA": "ديبا راو",
      "ml-IN": "ദീപ രാവു",
    },
    active: true,
    updatedAt: "2025-05-10T15:12:29Z",
  },
  {
    id: 12,
    nameLang: {
      "en-US": "Naveen Gupta",
      "kn-IN": "ನವೀನ್ ಗುಪ್ತಾ",
      "ta-IN": "நவீன் குப்தா",
      "hi-IN": "नवीन गुप्ता",
      "te-IN": "నవీన్ గుప్తా",
      "ar-SA": "نافين غوبتا",
      "ml-IN": "നവീൻ ഗുപ്ത",
    },
    active: true,
    updatedAt: "2024-06-15T11:28:14Z",
  },
  {
    id: 13,
    nameLang: {
      "en-US": "Sanjay Varma",
      "kn-IN": "ಸಂಜಯ್ ವರ್ಮಾ",
      "ta-IN": "சஞ்ஜய் வர்மா",
      "hi-IN": "संजय वर्मा",
      "te-IN": "సంజయ్ వర్మ",
      "ar-SA": "سانجاي فارما",
      "ml-IN": "സഞ്ജയ് വർമ",
    },
    active: false,
    updatedAt: "2025-01-25T14:50:22Z",
  },
  {
    id: 14,
    nameLang: {
      "en-US": "Asha Pillai",
      "kn-IN": "ಆಶಾ ಪಿಳ್ಳೈ",
      "ta-IN": "ஆஷா பிள்ளை",
      "hi-IN": "आशा पिल्लई",
      "te-IN": "ఆశా పిళ్ళై",
      "ar-SA": "آشا بيلاي",
      "ml-IN": "ആശ പിള്ള",
    },
    active: false,
    updatedAt: "2024-09-05T10:10:47Z",
  },
  {
    id: 15,
    nameLang: {
      "en-US": "Rahul Joshi",
      "kn-IN": "ರಾಹುಲ್ ಜೋಶಿ",
      "ta-IN": "ராகுல் ஜோஷி",
      "hi-IN": "राहुल जोशी",
      "te-IN": "రాహుల్ జోషి",
      "ar-SA": "راهول جوشي",
      "ml-IN": "രാഹുൽ ജോഷി",
    },
    active: false,
    updatedAt: "2025-03-15T16:33:09Z",
  },
  {
    id: 16,
    nameLang: {
      "en-US": "Divya Suresh",
      "kn-IN": "ದಿವ್ಯಾ ಸುರೇಶ್",
      "ta-IN": "திவ்யா சுரேஷ்",
      "hi-IN": "दिव्या सुरेश",
      "te-IN": "దివ్యా సురేష్",
      "ar-SA": "ديفيا سوريش",
      "ml-IN": "ദിവ്യ സുരേഷ്",
    },
    active: true,
    updatedAt: "2024-10-10T12:05:36Z",
  },
  {
    id: 17,
    nameLang: {
      "en-US": "Karthik Nair",
      "kn-IN": "ಕಾರ್ತಿಕ್ ನಾಯರ್",
      "ta-IN": "கார்த்திக் நாயர்",
      "hi-IN": "कार्तिक नायर",
      "te-IN": "కార్తీక్ నాయర్",
      "ar-SA": "كارثيك ناير",
      "ml-IN": "കാർത്തിക് നായർ",
    },
    active: true,
    updatedAt: "2025-02-10T09:22:51Z",
  },
  {
    id: 18,
    nameLang: {
      "en-US": "Sneha Varghese",
      "kn-IN": "ಸ್ನೇಹಾ ವರ್ಗೀಸ್",
      "ta-IN": "ஸ்னேஹா வர்கீஸ்",
      "hi-IN": "स्नेहा वर्गीस",
      "te-IN": "స్నేహా వర్గీస్",
      "ar-SA": "سنيها فارغيس",
      "ml-IN": "സ്നേഹ വർഗീസ്",
    },
    active: true,
    updatedAt: "2024-12-20T15:47:28Z",
  },
  {
    id: 19,
    nameLang: {
      "en-US": "Vijay Menon",
      "kn-IN": "ವಿಜಯ್ ಮೆನನ್",
      "ta-IN": "விஜய் மேனன்",
      "hi-IN": "विजय मेनन",
      "te-IN": "విజయ్ మేనన్",
      "ar-SA": "فيجاي مينون",
      "ml-IN": "വിജയ് മേനോൻ",
    },
    active: true,
    updatedAt: "2025-04-15T11:30:14Z",
  },
  {
    id: 20,
    nameLang: {
      "en-US": "Fatima Sheikh",
      "kn-IN": "ಫಾತಿಮಾ ಶೇಖ್",
      "ta-IN": "ஃபாத்திமா ஷேக்",
      "hi-IN": "फातिमा शेख",
      "te-IN": "ఫాతిమా షేక్",
      "ar-SA": "فاطمة شيخ",
      "ml-IN": "ഫാത്തിമ ഷെയ്ഖ്",
    },
    active: false,
    updatedAt: "2024-08-15T13:25:42Z",
  },
  {
    id: 21,
    nameLang: {
      "en-US": "Sunita Yadav",
      "kn-IN": "ಸುನೀತಾ ಯಾದವ್",
      "ta-IN": "சுனிதா யாதவ்",
      "hi-IN": "सुनीता यादव",
      "te-IN": "సునీతా యాదవ్",
      "ar-SA": "سونيتا ياداف",
      "ml-IN": "സുനിത യാദവ്",
    },
    active: true,
    updatedAt: "2024-07-10T14:18:27Z",
  },
  {
    id: 22,
    nameLang: {
      "en-US": "Mohammed Ali",
      "kn-IN": "ಮೊಹಮ್ಮದ್ ಅಲಿ",
      "ta-IN": "முகமது அலி",
      "hi-IN": "मोहम्मद अली",
      "te-IN": "మొహమ్మద్ అలీ",
      "ar-SA": "محمد علي",
      "ml-IN": "മുഹമ്മദ് അലി",
    },
    active: true,
    updatedAt: "2025-01-05T09:33:12Z",
  },
  {
    id: 23,
    nameLang: {
      "en-US": "Anita Thomas",
      "kn-IN": "ಅನಿತಾ ಥಾಮಸ್",
      "ta-IN": "அனிதா தாமஸ்",
      "hi-IN": "अनिता थॉमस",
      "te-IN": "అనితా థామస్",
      "ar-SA": "أنيتا توماس",
      "ml-IN": "അനിത തോമസ്",
    },
    active: false,
    updatedAt: "2024-11-25T16:45:50Z",
  },
  {
    id: 24,
    nameLang: {
      "en-US": "Ravi Shankar",
      "kn-IN": "ರವಿ ಶಂಕರ್",
      "ta-IN": "ரவி சங்கர்",
      "hi-IN": "रवि शंकर",
      "te-IN": "రవి శంకర్",
      "ar-SA": "رافي شانكار",
      "ml-IN": "രവി ശങ്കർ",
    },
    active: true,
    updatedAt: "2025-03-20T11:12:33Z",
  },
  {
    id: 25,
    nameLang: {
      "en-US": "Geetha Krishna",
      "kn-IN": "ಗೀತಾ ಕೃಷ್ಣ",
      "ta-IN": "கீதா கிருஷ்ணா",
      "hi-IN": "गीता कृष्णा",
      "te-IN": "గీతా కృష్ణ",
      "ar-SA": "جيثا كريشنا",
      "ml-IN": "ഗീത കൃഷ്ണ",
    },
    active: false,
    updatedAt: "2024-09-18T13:27:19Z",
  },
  {
    id: 26,
    nameLang: {
      "en-US": "Omar Farooq",
      "kn-IN": "ಒಮರ್ ಫಾರೂಕ್",
      "ta-IN": "ஒமர் பாரூக்",
      "hi-IN": "उमर फारूक",
      "te-IN": "ఒమర్ ఫరూఖ్",
      "ar-SA": "عمر فاروق",
      "ml-IN": "ഒമർ ഫാറൂഖ്",
    },
    active: true,
    updatedAt: "2025-02-15T10:50:41Z",
  },
  {
    id: 27,
    nameLang: {
      "en-US": "Pooja Nair",
      "kn-IN": "ಪೂಜಾ ನಾಯರ್",
      "ta-IN": "பூஜா நாயர்",
      "hi-IN": "पूजा नायर",
      "te-IN": "పూజా నాయర్",
      "ar-SA": "بوجا ناير",
      "ml-IN": "പൂജ നായർ",
    },
    active: true,
    updatedAt: "2024-08-05T15:30:22Z",
  },
  {
    id: 28,
    nameLang: {
      "en-US": "Vinod Pillai",
      "kn-IN": "ವಿನೋದ್ ಪಿಳ್ಳೈ",
      "ta-IN": "வினோத் பிள்ளை",
      "hi-IN": "विनोद पिल्लई",
      "te-IN": "వినోద్ పిళ్ళై",
      "ar-SA": "فينود بيلاي",
      "ml-IN": "വിനോദ് പിള്ള",
    },
    active: true,
    updatedAt: "2025-04-05T12:15:47Z",
  },
  {
    id: 29,
    nameLang: {
      "en-US": "Shalini Menon",
      "kn-IN": "ಶಾಲಿನಿ ಮೆನನ್",
      "ta-IN": "ஷாலினி மேனன்",
      "hi-IN": "शालिनी मेनन",
      "te-IN": "షాలినీ మేనన్",
      "ar-SA": "شاليني مينون",
      "ml-IN": "ഷാലിനി മേനോൻ",
    },
    active: true,
    updatedAt: "2024-10-30T09:40:13Z",
  },
  {
    id: 30,
    nameLang: {
      "en-US": "Abdul Rahman",
      "kn-IN": "ಅಬ್ದುಲ್ ರಹಮಾನ್",
      "ta-IN": "அப்துல் ரஹ்மான்",
      "hi-IN": "अब्दुल रहमान",
      "te-IN": "అబ్దుల్ రహ్మాన్",
      "ar-SA": "عبد الرحمن",
      "ml-IN": "അബ്ദുൽ റഹ്മാൻ",
    },
    active: true,
    updatedAt: "2025-05-01T14:22:09Z",
  },
];
