export const AppRouter = {
  DEFAULT: "",
  SIGN_UP: "/sign-up",
  HOME: "/",
  LOGIN: "/auth/login",
  FORGOT_PASSWORD: "/auth/forgotpassword",
  RESET_PASSWORD: "/auth/resetpassword",
  DASHBOARD: "/dashboard",
  PROFILE: "/profile",
  SUBSCRIPTION: "/subscription",
  TRANSACTIONS: "/transactions",
  ACCOUNT: "/account",
  ABOUTUS: "/about-us",
  CONTACTUS: "/contact-us",
  TERMS_AND_CONDITIONS: "/terms-conditions",
  PRIVACY_POLICIES: "/privacy-policy",
  PRICING_POLICY: "/disclaimer",
  RETURNS_REFUNDS: "/returns-refunds",
  SUBSCRIPTIONS: "/subscriptions",
  STORIES: "/stories",
  REDEEM: "/redeem",
  COMING_SOON: "/coming-soon",
  PAYMENT_VERIFY: "/payment-verify",
  QUESTION: "/ask-a-question",
  QUESTIONS: "/questions/all-qurries",
  CHAT_COVERSATION: "/questions/chat-conversation",
};

export const NonAuthRoutes = [
  AppRouter.DEFAULT,
  AppRouter.HOME,
  AppRouter.LOGIN,
  AppRouter.FORGOT_PASSWORD,
  AppRouter.RESET_PASSWORD,
  AppRouter.ABOUTUS,
  AppRouter.SUBSCRIPTION,
  AppRouter.CONTACTUS,
  AppRouter.TERMS_AND_CONDITIONS,
  AppRouter.PRIVACY_POLICIES,
  AppRouter.PRICING_POLICY,
  AppRouter.RETURNS_REFUNDS,
  AppRouter.COMING_SOON,
  AppRouter.QUESTION,
  AppRouter.QUESTIONS,
];
