export const AppRouter = {
  DEFAULT: "",
  SIGNUP: "/auth/signup",
  HOME: "/",
  LOGIN: "/auth/login",
  FORGOT_PASSWORD: "/auth/forgot-password",
  RESET_PASSWORD: "/auth/reset-password",
  DASHBOARD: "/dashboard",
  PROFILE: "/profile",
  SUBSCRIPTION: "/subscription",
  TRANSACTIONS: "/transactions",
  ACCOUNT: "/account",
  ABOUT_US: "/about-us",
  CONTACT_US: "/contact-us",
  TERMS_AND_CONDITIONS: "/terms-conditions",
  PRIVACY_POLICIES: "/privacy-policy",
  PRICING_POLICY: "/disclaimer",
  RETURNS_REFUNDS: "/returns-refunds",
  SUBSCRIPTIONS: "/subscriptions",
  REDEEM: "/redeem",
  COMING_SOON: "/coming-soon",
  PERMISSIONS: "/permissions",
  TEST_FORM: "/test-form",
};
