export const AppRouter = {
  DEFAULT: "",
  SIGN_UP: "/auth/signup",
  HOME: "/",
  LOGIN: "/auth/login",
  FORGOT_PASSWORD: "/auth/forgotpassword",
  RESET_PASSWORD: "/auth/resetpassword",
  DASHBOARD: "/dashboard",
  PROFILE: "/profile",
  SUBSCRIPTION: "/subscription",
  TRANSACTIONS: "/transactions",
  ACCOUNT: "/account",
  ABOUTUS: "/about-us",
  CONTACTUS: "/contact-us",
  TERMS_AND_CONDITIONS: "/terms-conditions",
  PRIVACY_POLICIES: "/privacy-policy",
  PRICING_POLICY: "/disclaimer",
  RETURNS_REFUNDS: "/returns-refunds",
  SUBSCRIPTIONS: "/subscriptions",
  REDEEM: "/redeem",
  COMING_SOON: "/coming-soon",
  PERMISSIONS: "/permissions",
  TESTFORM: "/test-form",
};
